apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - config.yaml
  - postgres.yaml
  - api.yaml
  - frontend.yaml
  - availability.yaml
  - ingress.yaml
  - network-policies.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: kind-task-platform
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
