apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: patch.yaml
labels:
  - pairs:
      app.kubernetes.io/environment: production
    includeSelectors: false
images:
  - name: kind.local/task-api
    newName: kind.local/task-api
    newTag: 1.0.0
  - name: kind.local/task-frontend
    newName: kind.local/task-frontend
    newTag: 1.0.0
