apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: task-app
data:
  APP_ENV: development
  LOG_LEVEL: DEBUG
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api
  namespace: task-app
spec:
  minReplicas: 1
  maxReplicas: 3
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend
  namespace: task-app
spec:
  minReplicas: 1
  maxReplicas: 3
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api
  namespace: task-app
spec:
  minAvailable: 0
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend
  namespace: task-app
spec:
  minAvailable: 0
